title:            Domo Factor
description:      Blog About Stuff
disqus_shortname: domofactor
reading_time:     false
words_per_minute: 200
#Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://domofactor.com

#Networking stuff
port:    4000
host:    127.0.0.1

# Owner/author information
owner:
  name:           Terrell Bromer
  avatar:         avatar2.jpg
  bio:            "I go drifting, fix linux servers and visit japan!"
  email:          terrell@domofactor.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        domofactor
  facebook:       pages/Domo-Factor/337082756302
  github:         terrellb
  stackexchange:  
  linkedin:       
  instagram:      domofactor
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  # google plus id, include the '+', eg +mmistakes
  google_plus:    #+yourid

# Background image to be tiled on all pages
background: background2.png

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
   - title: Subscribe
     url: /rss
  #- title: Theme Setup
  #  url: /theme-setup
  #- title: External Link
  #  url: http://mademistakes.com
  #  external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    US/Pacific
future:      true
highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", ".ruby-version", ".ruby-gemset"]
